name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you to contribute with our project resolving your first issue. 🎉"
        pr-message: "Amazing! We are so happy to you help us with your first pull request. Welcome! 🎉"
